#  ▄▄▄· ▄▄▌   ▄▄▄·  ▄▄· ▄▄▄  ▪  ▄▄▄▄▄▄▄▄▄▄ ▄· ▄▌
# ▐█ ▀█ ██•  ▐█ ▀█ ▐█ ▌▪▀▄ █·██ •██  •██  ▐█▪██▌
# ▄█▀▀█ ██▪  ▄█▀▀█ ██ ▄▄▐▀▀▄ ▐█· ▐█.▪ ▐█.▪▐█▌▐█▪
# ▐█ ▪▐▌▐█▌▐▌▐█ ▪▐▌▐███▌▐█•█▌▐█▌ ▐█▌· ▐█▌· ▐█▀·.
#  ▀  ▀ .▀▀▀  ▀  ▀ ·▀▀▀ .▀  ▀▀▀▀ ▀▀▀  ▀▀▀   ▀ • 
# Created by: Jaden Wu
# Github: @jadnw
# Email: jadenwu137@protonmail.com

import:
  - ~/.config/alacritty/theme.yml

window:
  title: alacritty
  dynamic_title: true
  class:
    instance: alacritty
    general: alacritty
  padding:
    x: 0
    y: 0
  dynamic_padding: true

scrolling:
  history: 2000
  multiplier: 3

font:
  normal:
    family: Josevka
    style: Book
  bold:
    family: Josevka
    style: Bold
  italic:
    family: Josevka
    tyle: Book Italic
  bold_italic:
    family: Josevka
    style: Bold Italic
  size: 12.5
  offset:
    x: 0
    y: 2

shell:
  program: /bin/fish

mouse:
  hide_when_typing: true
