# Winterfell for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#161f24'
    foreground: '#8eaaba'
    dim_foreground: '#61899e'
    bright_foreground: '#a5bbc8'
  cursor:
    text: '#161f24'
    cursor: '#62a5fd'
  vi_mode_cursor:
    text: '#161f24'
    cursor: '#62a5fd'
  search:
    matches:
      foreground: '#23323a'
      background: '#a47efd'
    focused_match:
      foreground: '#a47efd'
      background: '#23323a'
    bar:
      foreground: '#23323a'
      background: '#a47efd'
  hints:
    start:
      foreground: '#23323a'
      background: '#d9c57a'
    end:
      foreground: '#d9c57a'
      background: '#23323a'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: '#8eaaba'
    background: '#2a3b45'
  normal:
    black: '#3f5867'
    red: '#df6265'
    green: '#8ed084'
    yellow: '#d9c57a'
    blue: '#62a5fd'
    magenta: '#f474bc'
    cyan: '#60b8d8'
    white: '#b0c4ce'
  bright:
    black: '#3f5867'
    red: '#df6265'
    green: '#8ed084'
    yellow: '#d9c57a'
    blue: '#62a5fd'
    magenta: '#f474bc'
    cyan: '#60b8d8'
    white: '#b0c4ce'
    