#!/bin/fish

function get_power_state
  set addr (string split " " (bluetoothctl list | grep "default"))[2]
  set state (string split ": " (string trim -lr (bluetoothctl show $addr | grep "Powered")))[2]
  if test $state = "yes"
    echo on
  else
    echo off
  end
end

function toggle
  set state (get_power_state) 

  if test $state = "off"
    bluetoothctl power on &> /dev/null
    echo on
  else
    bluetoothctl power off &> /dev/null
    echo off
  end
end

switch $argv[1]
  case toggle
    toggle
  case state
    get_power_state
end
