#!/bin/fish

set theme $HOME/.config/awesome/externals/rofi/documents.rasi
set zathura_history_loc ~/.local/share/zathura/history 

killall -q rofi

set docs (cat ~/.local/share/zathura/history | grep -Po "\[\K[^\]]*" | grep "/home/")

if test -z "$docs"
  notify-send --app-name="Zathura" --icon="zathura" "No recents documents" "Cannot find any documents in your zathura history"
  exit 0
end

set opt (printf "%s\n" $docs | rofi -dmenu -p "Zathura" -theme $theme)

if test -z $opt
  exit 0
end

zathura $opt
exit 0
